default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>  
  pool: 5

development:
  <<: *default
  database: consult_gpt_development

test:
  <<: *default
  database: consult_gpt_test

production:
  <<: *default
  database: consult_gpt_production
  password: <%= ENV['POSTGRES_PASSWORD'] %>