name: "Ruby on Rails CI"
on:
  push:
jobs:      
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bin/qa
      - name: Set pipeline status
        if: always()
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { context } = require('@actions/github');
            const octokit = context.getOctokit();
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = context.sha;
            const result = process.exitCode === 0 ? 'success' : 'failure';
            octokit.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: result,
              context: 'Ruby on Rails CI',
              description: 'Pipeline status'
            });
